In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
First1={
    "area":[2600,3000,3200,3600,4000],
    "bedrooms":[3,4,"NaN",3,5],
    "age":[20,15,18,30,8],
    "price":[550000,565000,610000,595000,760000]
}
df=pd.DataFrame(First1)


In [3]:
df

area bedrooms  age   price
0  2600        3   20  550000
1  3000        4   15  565000
2  3200      NaN   18  610000
3  3600        3   30  595000
4  4000        5    8  760000

In [4]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

3

In [9]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms,inplace=False)
df

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         3   15  565000
2  3200         3   18  610000
3  3600         3   30  595000
4  4000         3    8  760000

In [10]:
reg=linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [11]:
reg.coef_

array([  118.40231951,     0.        , -4718.06464295])

In [12]:
reg.intercept_

313509.1685153465

In [13]:
reg.predict([[3000,3,15]])

C:\Users\TUSHAR\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([597945.15739519])

In [15]:
118.40231951*3000+ 0.  *3+-4718.06464295*15+313509.1685153465

597945.1574010965

In [16]:
reg.predict([[2500,4,5]])

C:\Users\TUSHAR\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([585924.64407065])